#!/bin/bash

list=$(ls)
all_yes=false
for line in $list
do
    new_name=$(sed 's/.*/\L&/' <<< $line)
    if [ $all_yes = true ]; then
        mv $line $new_name
    fi
    next=false
    while [ $next = false -a $all_yes = false ]; do
        echo "Rename $line to $new_name?"
        echo "(y/n) (ay/an)"
        read go_on
        if [ $go_on = "y" ]; then
            mv $line $new_name
            next=true
        elif [ $go_on = "n" ]; then
            echo "next"; next=true
        elif [ $go_on = "ay" ]; then
            echo "Yes to all"
            all_yes=true
        elif [ $go_on = "an" ]; then
            echo "No to all"
            exit 0
        else
            echo "Only y/n are accepted"
        fi
    done
done      
